### PR TITLE
Opticals Repository Cleaned up 

### PR DESCRIPTION
**Pull request by lewishamulton**
**Changes Made**
- lidar_ouput replaced with opticane simulation scripts; removed demo2 and dummylidardata scripts since they were demo2 specific scripts and were not relevant to the final product (i.e primarily used the turtlebot and ROS functionality)

- demo3 and feedbackutils scripts were mistakenly added to the top level directory- this was an issue with committing after a previous PR. Newer vers of demo3 and feedbackutils were moved from top level to relevant directory within repo.

- demo3.py renamed to main.py; central and sole script ran by the hardware prototype of opticane

### CODE REVIEW

**Review by austin-pan — COMMENTED** [review]
Thanks for doing this @lewishamulton! Looking good and almost there! Just a few changes:
* Can we rename `opticane simulation scripts` to `features`
* Can we move `speech_recognition/speechCommand.py` into `features`
* Delete `speech_recognition/` now that it's empy
* Can we rename `raspberry pi controllers` to `rpi_controllers`

**Comment by austin-pan** [comment]
Also, can you add an empty file `__init__.py` into `features`? That will allow `features` to be a `python` package that we could theoretically import from later if we add the `features` file path to the `PYTHONPATH` environment variable 😄

**Comment by lewishamulton** [comment]
I think that's most of the changes made

**Comment by lewishamulton** [comment]
Final changes made
 - raspberry pi controllers changed to rpi_controllers

**Review by austin-pan — APPROVED** [review]
LGTM!

**Pull request merged**
